INSERT INTO villes (idVille, label) VALUES(1, "Aïn Harrouda");
INSERT INTO villes (idVille, label) VALUES(2, "Ben Yakhlef");
INSERT INTO villes (idVille, label) VALUES(3, "Bouskoura");
INSERT INTO villes (idVille, label) VALUES(4, "Casablanca");
INSERT INTO villes (idVille, label) VALUES(5, "Médiouna");
INSERT INTO villes (idVille, label) VALUES(6, "Mohammadia");
INSERT INTO villes (idVille, label) VALUES(7, "Tit Mellil");
INSERT INTO villes (idVille, label) VALUES(8, "Ben Yakhlef");
INSERT INTO villes (idVille, label) VALUES(9, "Bejaâd");
INSERT INTO villes (idVille, label) VALUES(10, "Ben Ahmed");
INSERT INTO villes (idVille, label) VALUES(11, "Benslimane");
INSERT INTO villes (idVille, label) VALUES(12, "Berrechid");
INSERT INTO villes (idVille, label) VALUES(13, "Boujniba");
INSERT INTO villes (idVille, label) VALUES(14, "Boulanouare");
INSERT INTO villes (idVille, label) VALUES(15, "Bouznika");
INSERT INTO villes (idVille, label) VALUES(16, "Deroua");
INSERT INTO villes (idVille, label) VALUES(17, "El Borouj");
INSERT INTO villes (idVille, label) VALUES(18, "El Gara");
INSERT INTO villes (idVille, label) VALUES(19, "Guisser");
INSERT INTO villes (idVille, label) VALUES(20, "Hattane");
INSERT INTO villes (idVille, label) VALUES(21, "Khouribga");
INSERT INTO villes (idVille, label) VALUES(22, "Loulad");
INSERT INTO villes (idVille, label) VALUES(23, "Oued Zem");
INSERT INTO villes (idVille, label) VALUES(24, "Oulad Abbou");
INSERT INTO villes (idVille, label) VALUES(25, "Oulad HRiz Sahel");
INSERT INTO villes (idVille, label) VALUES(26, "Oulad Mrah");
INSERT INTO villes (idVille, label) VALUES(27, "Oulad Saïd");
INSERT INTO villes (idVille, label) VALUES(28, "Oulad Sidi Ben Daoud");
INSERT INTO villes (idVille, label) VALUES(29, "Ras El Aïn");
INSERT INTO villes (idVille, label) VALUES(30, "Settat");
INSERT INTO villes (idVille, label) VALUES(31, "Sidi Rahhal Chataï");
INSERT INTO villes (idVille, label) VALUES(32, "Soualem");
INSERT INTO villes (idVille, label) VALUES(33, "Azemmour");
INSERT INTO villes (idVille, label) VALUES(34, "Bir Jdid");
INSERT INTO villes (idVille, label) VALUES(35, "Bouguedra");
INSERT INTO villes (idVille, label) VALUES(36, "Echemmaia");
INSERT INTO villes (idVille, label) VALUES(37, "El Jadida");
INSERT INTO villes (idVille, label) VALUES(38, "Hrara");
INSERT INTO villes (idVille, label) VALUES(39, "Ighoud");
INSERT INTO villes (idVille, label) VALUES(40, "Jamâat Shaim");
INSERT INTO villes (idVille, label) VALUES(41, "Jorf Lasfar");
INSERT INTO villes (idVille, label) VALUES(42, "Khemis Zemamra");
INSERT INTO villes (idVille, label) VALUES(43, "Laaounate");
INSERT INTO villes (idVille, label) VALUES(44, "Moulay Abdallah");
INSERT INTO villes (idVille, label) VALUES(45, "Oualidia");
INSERT INTO villes (idVille, label) VALUES(46, "Oulad Amrane");
INSERT INTO villes (idVille, label) VALUES(47, "Oulad Frej");
INSERT INTO villes (idVille, label) VALUES(48, "Oulad Ghadbane");
INSERT INTO villes (idVille, label) VALUES(49, "Safi");
INSERT INTO villes (idVille, label) VALUES(50, "Sebt El Maârif");
INSERT INTO villes (idVille, label) VALUES(51, "Sebt Gzoula");
INSERT INTO villes (idVille, label) VALUES(52, "Sidi Ahmed");
INSERT INTO villes (idVille, label) VALUES(53, "Sidi Ali Ban Hamdouche");
INSERT INTO villes (idVille, label) VALUES(54, "Sidi Bennour");
INSERT INTO villes (idVille, label) VALUES(55, "Sidi Bouzid");
INSERT INTO villes (idVille, label) VALUES(56, "Sidi Smaïl");
INSERT INTO villes (idVille, label) VALUES(57, "Youssoufia");
INSERT INTO villes (idVille, label) VALUES(58, "Fès");
INSERT INTO villes (idVille, label) VALUES(59, "Aïn Cheggag");
INSERT INTO villes (idVille, label) VALUES(60, "Bhalil");
INSERT INTO villes (idVille, label) VALUES(61, "Boulemane");
INSERT INTO villes (idVille, label) VALUES(62, "El Menzel");
INSERT INTO villes (idVille, label) VALUES(63, "Guigou");
INSERT INTO villes (idVille, label) VALUES(64, "Imouzzer Kandar");
INSERT INTO villes (idVille, label) VALUES(65, "Imouzzer Marmoucha");
INSERT INTO villes (idVille, label) VALUES(66, "Missour");
INSERT INTO villes (idVille, label) VALUES(67, "Moulay Yaâcoub");
INSERT INTO villes (idVille, label) VALUES(68, "Ouled Tayeb");
INSERT INTO villes (idVille, label) VALUES(69, "Outat El Haj");
INSERT INTO villes (idVille, label) VALUES(70, "Ribate El Kheir");
INSERT INTO villes (idVille, label) VALUES(71, "Séfrou");
INSERT INTO villes (idVille, label) VALUES(72, "Skhinate");
INSERT INTO villes (idVille, label) VALUES(73, "Tafajight");
INSERT INTO villes (idVille, label) VALUES(74, "Arbaoua");
INSERT INTO villes (idVille, label) VALUES(75, "Aïn Dorij");
INSERT INTO villes (idVille, label) VALUES(76, "Dar Gueddari");
INSERT INTO villes (idVille, label) VALUES(77, "Had Kourt");
INSERT INTO villes (idVille, label) VALUES(78, "Jorf El Melha");
INSERT INTO villes (idVille, label) VALUES(79, "Kénitra");
INSERT INTO villes (idVille, label) VALUES(80, "Khenichet");
INSERT INTO villes (idVille, label) VALUES(81, "Lalla Mimouna");
INSERT INTO villes (idVille, label) VALUES(82, "Mechra Bel Ksiri");
INSERT INTO villes (idVille, label) VALUES(83, "Mehdia");
INSERT INTO villes (idVille, label) VALUES(84, "Moulay Bousselham");
INSERT INTO villes (idVille, label) VALUES(85, "Sidi Allal Tazi");
INSERT INTO villes (idVille, label) VALUES(86, "Sidi Kacem");
INSERT INTO villes (idVille, label) VALUES(87, "Sidi Slimane");
INSERT INTO villes (idVille, label) VALUES(88, "Sidi Taibi");
INSERT INTO villes (idVille, label) VALUES(89, "Sidi Yahya El Gharb");
INSERT INTO villes (idVille, label) VALUES(90, "Souk El Arbaa");
INSERT INTO villes (idVille, label) VALUES(91, "Akka");
INSERT INTO villes (idVille, label) VALUES(92, "Assa");
INSERT INTO villes (idVille, label) VALUES(93, "Bouizakarne");
INSERT INTO villes (idVille, label) VALUES(94, "El Ouatia");
INSERT INTO villes (idVille, label) VALUES(95, "Es-Semara");
INSERT INTO villes (idVille, label) VALUES(96, "Fam El Hisn");
INSERT INTO villes (idVille, label) VALUES(97, "Foum Zguid");
INSERT INTO villes (idVille, label) VALUES(98, "Guelmim");
INSERT INTO villes (idVille, label) VALUES(99, "Taghjijt");
INSERT INTO villes (idVille, label) VALUES(100, "Tan-Tan");
INSERT INTO villes (idVille, label) VALUES(101, "Tata");
INSERT INTO villes (idVille, label) VALUES(102, "Zag");
INSERT INTO villes (idVille, label) VALUES(103, "Marrakech");
INSERT INTO villes (idVille, label) VALUES(104, "Ait Daoud");
INSERT INTO villes (idVille, label) VALUES(115, "Amizmiz");
INSERT INTO villes (idVille, label) VALUES(116, "Assahrij");
INSERT INTO villes (idVille, label) VALUES(117, "Aït Ourir");
INSERT INTO villes (idVille, label) VALUES(118, "Ben Guerir");
INSERT INTO villes (idVille, label) VALUES(119, "Chichaoua");
INSERT INTO villes (idVille, label) VALUES(120, "El Hanchane");
INSERT INTO villes (idVille, label) VALUES(121, "El Kelaâ des Sraghna");
INSERT INTO villes (idVille, label) VALUES(122, "Essaouira");
INSERT INTO villes (idVille, label) VALUES(123, "Fraïta");
INSERT INTO villes (idVille, label) VALUES(124, "Ghmate");
INSERT INTO villes (idVille, label) VALUES(125, "Ighounane");
INSERT INTO villes (idVille, label) VALUES(126, "Imintanoute");
INSERT INTO villes (idVille, label) VALUES(127, "Kattara");
INSERT INTO villes (idVille, label) VALUES(128, "Lalla Takerkoust");
INSERT INTO villes (idVille, label) VALUES(129, "Loudaya");
INSERT INTO villes (idVille, label) VALUES(130, "Lâattaouia");
INSERT INTO villes (idVille, label) VALUES(131, "Moulay Brahim");
INSERT INTO villes (idVille, label) VALUES(132, "Mzouda");
INSERT INTO villes (idVille, label) VALUES(133, "Ounagha");
INSERT INTO villes (idVille, label) VALUES(134, "Sid LMokhtar");
INSERT INTO villes (idVille, label) VALUES(135, "Sid Zouin");
INSERT INTO villes (idVille, label) VALUES(136, "Sidi Abdallah Ghiat");
INSERT INTO villes (idVille, label) VALUES(137, "Sidi Bou Othmane");
INSERT INTO villes (idVille, label) VALUES(138, "Sidi Rahhal");
INSERT INTO villes (idVille, label) VALUES(139, "Skhour Rehamna");
INSERT INTO villes (idVille, label) VALUES(140, "Smimou");
INSERT INTO villes (idVille, label) VALUES(141, "Tafetachte");
INSERT INTO villes (idVille, label) VALUES(142, "Tahannaout");
INSERT INTO villes (idVille, label) VALUES(143, "Talmest");
INSERT INTO villes (idVille, label) VALUES(144, "Tamallalt");
INSERT INTO villes (idVille, label) VALUES(145, "Tamanar");
INSERT INTO villes (idVille, label) VALUES(146, "Tamansourt");
INSERT INTO villes (idVille, label) VALUES(147, "Tameslouht");
INSERT INTO villes (idVille, label) VALUES(148, "Tanalt");
INSERT INTO villes (idVille, label) VALUES(149, "Zeubelemok");
INSERT INTO villes (idVille, label) VALUES(150, "Meknès‎");
INSERT INTO villes (idVille, label) VALUES(151, "Khénifra");
INSERT INTO villes (idVille, label) VALUES(152, "Agourai");
INSERT INTO villes (idVille, label) VALUES(153, "Ain Taoujdate");
INSERT INTO villes (idVille, label) VALUES(154, "MyAliCherif");
INSERT INTO villes (idVille, label) VALUES(155, "Rissani");
INSERT INTO villes (idVille, label) VALUES(156, "Amalou Ighriben");
INSERT INTO villes (idVille, label) VALUES(157, "Aoufous");
INSERT INTO villes (idVille, label) VALUES(158, "Arfoud");
INSERT INTO villes (idVille, label) VALUES(159, "Azrou");
INSERT INTO villes (idVille, label) VALUES(160, "Aïn Jemaa");
INSERT INTO villes (idVille, label) VALUES(161, "Aïn Karma");
INSERT INTO villes (idVille, label) VALUES(162, "Aïn Leuh");
INSERT INTO villes (idVille, label) VALUES(163, "Aït Boubidmane");
INSERT INTO villes (idVille, label) VALUES(164, "Aït Ishaq");
INSERT INTO villes (idVille, label) VALUES(165, "Boudnib");
INSERT INTO villes (idVille, label) VALUES(166, "Boufakrane");
INSERT INTO villes (idVille, label) VALUES(167, "Boumia");
INSERT INTO villes (idVille, label) VALUES(168, "El Hajeb");
INSERT INTO villes (idVille, label) VALUES(169, "Elkbab");
INSERT INTO villes (idVille, label) VALUES(170, "Er-Rich");
INSERT INTO villes (idVille, label) VALUES(171, "Errachidia");
INSERT INTO villes (idVille, label) VALUES(172, "Gardmit");
INSERT INTO villes (idVille, label) VALUES(173, "Goulmima");
INSERT INTO villes (idVille, label) VALUES(174, "Gourrama");
INSERT INTO villes (idVille, label) VALUES(175, "Had Bouhssoussen");
INSERT INTO villes (idVille, label) VALUES(176, "Haj Kaddour");
INSERT INTO villes (idVille, label) VALUES(177, "Ifrane");
INSERT INTO villes (idVille, label) VALUES(178, "Itzer");
INSERT INTO villes (idVille, label) VALUES(179, "Jorf");
INSERT INTO villes (idVille, label) VALUES(180, "Kehf Nsour");
INSERT INTO villes (idVille, label) VALUES(181, "Kerrouchen");
INSERT INTO villes (idVille, label) VALUES(182, "Mhaya");
INSERT INTO villes (idVille, label) VALUES(183, "Mrirt");
INSERT INTO villes (idVille, label) VALUES(184, "Midelt");
INSERT INTO villes (idVille, label) VALUES(185, "Moulay Ali Cherif");
INSERT INTO villes (idVille, label) VALUES(186, "Moulay Bouazza");
INSERT INTO villes (idVille, label) VALUES(187, "Moulay Idriss Zerhoun");
INSERT INTO villes (idVille, label) VALUES(188, "Moussaoua");
INSERT INTO villes (idVille, label) VALUES(189, "NZalat Bni Amar");
INSERT INTO villes (idVille, label) VALUES(190, "Ouaoumana");
INSERT INTO villes (idVille, label) VALUES(191, "Oued Ifrane");
INSERT INTO villes (idVille, label) VALUES(192, "Sabaa Aiyoun");
INSERT INTO villes (idVille, label) VALUES(193, "Sebt Jahjouh");
INSERT INTO villes (idVille, label) VALUES(194, "Sidi Addi");
INSERT INTO villes (idVille, label) VALUES(195, "Tichoute");
INSERT INTO villes (idVille, label) VALUES(196, "Tighassaline");
INSERT INTO villes (idVille, label) VALUES(197, "Tighza");
INSERT INTO villes (idVille, label) VALUES(198, "Timahdite");
INSERT INTO villes (idVille, label) VALUES(199, "Tinejdad");
INSERT INTO villes (idVille, label) VALUES(200, "Tizguite");
INSERT INTO villes (idVille, label) VALUES(201, "Toulal");
INSERT INTO villes (idVille, label) VALUES(202, "Tounfite");
INSERT INTO villes (idVille, label) VALUES(203, "Zaouia dIfrane");
INSERT INTO villes (idVille, label) VALUES(204, "Zaïda");
INSERT INTO villes (idVille, label) VALUES(205, "Ahfir");
INSERT INTO villes (idVille, label) VALUES(206, "Aklim");
INSERT INTO villes (idVille, label) VALUES(207, "Al Aroui");
INSERT INTO villes (idVille, label) VALUES(208, "Aïn Bni Mathar");
INSERT INTO villes (idVille, label) VALUES(209, "Aïn Erreggada");
INSERT INTO villes (idVille, label) VALUES(210, "Ben Taïeb");
INSERT INTO villes (idVille, label) VALUES(211, "Berkane");
INSERT INTO villes (idVille, label) VALUES(212, "Bni Ansar");
INSERT INTO villes (idVille, label) VALUES(213, "Bni Chiker");
INSERT INTO villes (idVille, label) VALUES(214, "Bni Drar");
INSERT INTO villes (idVille, label) VALUES(215, "Bni Tadjite");
INSERT INTO villes (idVille, label) VALUES(216, "Bouanane");
INSERT INTO villes (idVille, label) VALUES(217, "Bouarfa");
INSERT INTO villes (idVille, label) VALUES(218, "Bouhdila");
INSERT INTO villes (idVille, label) VALUES(219, "Dar El Kebdani");
INSERT INTO villes (idVille, label) VALUES(220, "Debdou");
INSERT INTO villes (idVille, label) VALUES(221, "Douar Kannine");
INSERT INTO villes (idVille, label) VALUES(222, "Driouch");
INSERT INTO villes (idVille, label) VALUES(223, "El Aïoun Sidi Mellouk");
INSERT INTO villes (idVille, label) VALUES(224, "Farkhana");
INSERT INTO villes (idVille, label) VALUES(225, "Figuig");
INSERT INTO villes (idVille, label) VALUES(226, "Ihddaden");
INSERT INTO villes (idVille, label) VALUES(227, "Jaâdar");
INSERT INTO villes (idVille, label) VALUES(228, "Jerada");
INSERT INTO villes (idVille, label) VALUES(229, "Kariat Arekmane");
INSERT INTO villes (idVille, label) VALUES(230, "Kassita");
INSERT INTO villes (idVille, label) VALUES(231, "Kerouna");
INSERT INTO villes (idVille, label) VALUES(232, "Laâtamna");
INSERT INTO villes (idVille, label) VALUES(233, "Madagh");
INSERT INTO villes (idVille, label) VALUES(234, "Midar");
INSERT INTO villes (idVille, label) VALUES(235, "Nador");
INSERT INTO villes (idVille, label) VALUES(236, "Naima");
INSERT INTO villes (idVille, label) VALUES(237, "Oued Heimer");
INSERT INTO villes (idVille, label) VALUES(238, "Oujda");
INSERT INTO villes (idVille, label) VALUES(239, "Ras El Ma");
INSERT INTO villes (idVille, label) VALUES(240, "Saïdia");
INSERT INTO villes (idVille, label) VALUES(241, "Selouane");
INSERT INTO villes (idVille, label) VALUES(242, "Sidi Boubker");
INSERT INTO villes (idVille, label) VALUES(243, "Sidi Slimane Echcharaa");
INSERT INTO villes (idVille, label) VALUES(244, "Talsint");
INSERT INTO villes (idVille, label) VALUES(245, "Taourirt");
INSERT INTO villes (idVille, label) VALUES(246, "Tendrara");
INSERT INTO villes (idVille, label) VALUES(247, "Tiztoutine");
INSERT INTO villes (idVille, label) VALUES(248, "Touima");
INSERT INTO villes (idVille, label) VALUES(249, "Touissit");
INSERT INTO villes (idVille, label) VALUES(250, "Zaïo");
INSERT INTO villes (idVille, label) VALUES(251, "Zeghanghane");
INSERT INTO villes (idVille, label) VALUES(252, "Rabat");
INSERT INTO villes (idVille, label) VALUES(253, "Salé");
INSERT INTO villes (idVille, label) VALUES(254, "Ain El Aouda");
INSERT INTO villes (idVille, label) VALUES(255, "Harhoura");
INSERT INTO villes (idVille, label) VALUES(256, "Khémisset");
INSERT INTO villes (idVille, label) VALUES(257, "Oulmès");
INSERT INTO villes (idVille, label) VALUES(258, "Rommani");
INSERT INTO villes (idVille, label) VALUES(259, "Sidi Allal El Bahraoui");
INSERT INTO villes (idVille, label) VALUES(260, "Sidi Bouknadel");
INSERT INTO villes (idVille, label) VALUES(261, "Skhirate");
INSERT INTO villes (idVille, label) VALUES(262, "Tamesna");
INSERT INTO villes (idVille, label) VALUES(263, "Témara");
INSERT INTO villes (idVille, label) VALUES(264, "Tiddas");
INSERT INTO villes (idVille, label) VALUES(265, "Tiflet");
INSERT INTO villes (idVille, label) VALUES(266, "Touarga");
INSERT INTO villes (idVille, label) VALUES(267, "Agadir");
INSERT INTO villes (idVille, label) VALUES(268, "Agdz");
INSERT INTO villes (idVille, label) VALUES(269, "Agni Izimmer");
INSERT INTO villes (idVille, label) VALUES(270, "Aït Melloul");
INSERT INTO villes (idVille, label) VALUES(271, "Alnif");
INSERT INTO villes (idVille, label) VALUES(272, "Anzi");
INSERT INTO villes (idVille, label) VALUES(273, "Aoulouz");
INSERT INTO villes (idVille, label) VALUES(274, "Aourir");
INSERT INTO villes (idVille, label) VALUES(275, "Arazane");
INSERT INTO villes (idVille, label) VALUES(276, "Aït Baha");
INSERT INTO villes (idVille, label) VALUES(277, "Aït Iaâza");
INSERT INTO villes (idVille, label) VALUES(278, "Aït Yalla");
INSERT INTO villes (idVille, label) VALUES(279, "Ben Sergao");
INSERT INTO villes (idVille, label) VALUES(280, "Biougra");
INSERT INTO villes (idVille, label) VALUES(281, "Boumalne-Dadès");
INSERT INTO villes (idVille, label) VALUES(282, "Dcheira El Jihadia");
INSERT INTO villes (idVille, label) VALUES(283, "Drargua");
INSERT INTO villes (idVille, label) VALUES(284, "El Guerdane");
INSERT INTO villes (idVille, label) VALUES(285, "Harte Lyamine");
INSERT INTO villes (idVille, label) VALUES(286, "Ida Ougnidif");
INSERT INTO villes (idVille, label) VALUES(287, "Ifri");
INSERT INTO villes (idVille, label) VALUES(288, "Igdamen");
INSERT INTO villes (idVille, label) VALUES(289, "Ighil nOumgoun");
INSERT INTO villes (idVille, label) VALUES(290, "Imassine");
INSERT INTO villes (idVille, label) VALUES(291, "Inezgane");
INSERT INTO villes (idVille, label) VALUES(292, "Irherm");
INSERT INTO villes (idVille, label) VALUES(293, "Kelaat-MGouna");
INSERT INTO villes (idVille, label) VALUES(294, "Lakhsas");
INSERT INTO villes (idVille, label) VALUES(295, "Lakhsass");
INSERT INTO villes (idVille, label) VALUES(296, "Lqliâa");
INSERT INTO villes (idVille, label) VALUES(297, "Msemrir");
INSERT INTO villes (idVille, label) VALUES(298, "Massa (Maroc)");
INSERT INTO villes (idVille, label) VALUES(299, "Megousse");
INSERT INTO villes (idVille, label) VALUES(300, "Ouarzazate");
INSERT INTO villes (idVille, label) VALUES(301, "Oulad Berhil");
INSERT INTO villes (idVille, label) VALUES(302, "Oulad Teïma");
INSERT INTO villes (idVille, label) VALUES(303, "Sarghine");
INSERT INTO villes (idVille, label) VALUES(304, "Sidi Ifni");
INSERT INTO villes (idVille, label) VALUES(305, "Skoura");
INSERT INTO villes (idVille, label) VALUES(306, "Tabounte");
INSERT INTO villes (idVille, label) VALUES(307, "Tafraout");
INSERT INTO villes (idVille, label) VALUES(308, "Taghzout");
INSERT INTO villes (idVille, label) VALUES(309, "Tagzen");
INSERT INTO villes (idVille, label) VALUES(310, "Taliouine");
INSERT INTO villes (idVille, label) VALUES(311, "Tamegroute");
INSERT INTO villes (idVille, label) VALUES(312, "Tamraght");
INSERT INTO villes (idVille, label) VALUES(313, "Tanoumrite Nkob Zagora");
INSERT INTO villes (idVille, label) VALUES(314, "Taourirt ait zaghar");
INSERT INTO villes (idVille, label) VALUES(315, "Taroudannt");
INSERT INTO villes (idVille, label) VALUES(316, "Temsia");
INSERT INTO villes (idVille, label) VALUES(317, "Tifnit");
INSERT INTO villes (idVille, label) VALUES(318, "Tisgdal");
INSERT INTO villes (idVille, label) VALUES(319, "Tiznit");
INSERT INTO villes (idVille, label) VALUES(320, "Toundoute");
INSERT INTO villes (idVille, label) VALUES(321, "Zagora");
INSERT INTO villes (idVille, label) VALUES(322, "Afourar");
INSERT INTO villes (idVille, label) VALUES(323, "Aghbala");
INSERT INTO villes (idVille, label) VALUES(324, "Azilal");
INSERT INTO villes (idVille, label) VALUES(325, "Aït Majden");
INSERT INTO villes (idVille, label) VALUES(326, "Beni Ayat");
INSERT INTO villes (idVille, label) VALUES(327, "Béni Mellal");
INSERT INTO villes (idVille, label) VALUES(328, "Bin elouidane");
INSERT INTO villes (idVille, label) VALUES(329, "Bradia");
INSERT INTO villes (idVille, label) VALUES(330, "Bzou");
INSERT INTO villes (idVille, label) VALUES(331, "Dar Oulad Zidouh");
INSERT INTO villes (idVille, label) VALUES(332, "Demnate");
INSERT INTO villes (idVille, label) VALUES(333, "Draa");
INSERT INTO villes (idVille, label) VALUES(334, "El Ksiba");
INSERT INTO villes (idVille, label) VALUES(335, "Foum Jamaa");
INSERT INTO villes (idVille, label) VALUES(336, "Fquih Ben Salah");
INSERT INTO villes (idVille, label) VALUES(337, "Kasba Tadla");
INSERT INTO villes (idVille, label) VALUES(338, "Ouaouizeght");
INSERT INTO villes (idVille, label) VALUES(339, "Oulad Ayad");
INSERT INTO villes (idVille, label) VALUES(340, "Oulad MBarek");
INSERT INTO villes (idVille, label) VALUES(341, "Oulad Yaich");
INSERT INTO villes (idVille, label) VALUES(342, "Sidi Jaber");
INSERT INTO villes (idVille, label) VALUES(343, "Souk Sebt Oulad Nemma");
INSERT INTO villes (idVille, label) VALUES(344, "Zaouïat Cheikh");
INSERT INTO villes (idVille, label) VALUES(345, "Tanger‎");
INSERT INTO villes (idVille, label) VALUES(346, "Tétouan‎");
INSERT INTO villes (idVille, label) VALUES(347, "Akchour");
INSERT INTO villes (idVille, label) VALUES(348, "Assilah");
INSERT INTO villes (idVille, label) VALUES(349, "Bab Berred");
INSERT INTO villes (idVille, label) VALUES(350, "Bab Taza");
INSERT INTO villes (idVille, label) VALUES(351, "Brikcha");
INSERT INTO villes (idVille, label) VALUES(352, "Chefchaouen");
INSERT INTO villes (idVille, label) VALUES(353, "Dar Bni Karrich");
INSERT INTO villes (idVille, label) VALUES(354, "Dar Chaoui");
INSERT INTO villes (idVille, label) VALUES(355, "Fnideq");
INSERT INTO villes (idVille, label) VALUES(356, "Gueznaia");
INSERT INTO villes (idVille, label) VALUES(357, "Jebha");
INSERT INTO villes (idVille, label) VALUES(358, "Karia");
INSERT INTO villes (idVille, label) VALUES(359, "Khémis Sahel");
INSERT INTO villes (idVille, label) VALUES(360, "Ksar El Kébir");
INSERT INTO villes (idVille, label) VALUES(361, "Larache");
INSERT INTO villes (idVille, label) VALUES(362, "Mdiq");
INSERT INTO villes (idVille, label) VALUES(363, "Martil");
INSERT INTO villes (idVille, label) VALUES(364, "Moqrisset");
INSERT INTO villes (idVille, label) VALUES(365, "Oued Laou");
INSERT INTO villes (idVille, label) VALUES(366, "Oued Rmel");
INSERT INTO villes (idVille, label) VALUES(367, "Ouazzane");
INSERT INTO villes (idVille, label) VALUES(368, "Point Cires");
INSERT INTO villes (idVille, label) VALUES(369, "Sidi Lyamani");
INSERT INTO villes (idVille, label) VALUES(370, "Sidi Mohamed ben Abdallah el-Raisuni");
INSERT INTO villes (idVille, label) VALUES(371, "Zinat");
INSERT INTO villes (idVille, label) VALUES(372, "Ajdir‎");
INSERT INTO villes (idVille, label) VALUES(373, "Aknoul‎");
INSERT INTO villes (idVille, label) VALUES(374, "Al Hoceïma‎");
INSERT INTO villes (idVille, label) VALUES(375, "Aït Hichem‎");
INSERT INTO villes (idVille, label) VALUES(376, "Bni Bouayach‎");
INSERT INTO villes (idVille, label) VALUES(377, "Bni Hadifa‎");
INSERT INTO villes (idVille, label) VALUES(378, "Ghafsai‎");
INSERT INTO villes (idVille, label) VALUES(379, "Guercif‎");
INSERT INTO villes (idVille, label) VALUES(380, "Imzouren‎");
INSERT INTO villes (idVille, label) VALUES(381, "Inahnahen‎");
INSERT INTO villes (idVille, label) VALUES(382, "Issaguen (Ketama)‎");
INSERT INTO villes (idVille, label) VALUES(383, "Karia (El Jadida)‎");
INSERT INTO villes (idVille, label) VALUES(384, "Karia Ba Mohamed‎");
INSERT INTO villes (idVille, label) VALUES(385, "Oued Amlil‎");
INSERT INTO villes (idVille, label) VALUES(386, "Oulad Zbair‎");
INSERT INTO villes (idVille, label) VALUES(387, "Tahla‎");
INSERT INTO villes (idVille, label) VALUES(388, "Tala Tazegwaght‎");
INSERT INTO villes (idVille, label) VALUES(389, "Tamassint‎");
INSERT INTO villes (idVille, label) VALUES(390, "Taounate‎");
INSERT INTO villes (idVille, label) VALUES(391, "Targuist‎");
INSERT INTO villes (idVille, label) VALUES(392, "Taza‎");
INSERT INTO villes (idVille, label) VALUES(393, "Taïnaste‎");
INSERT INTO villes (idVille, label) VALUES(394, "Thar Es-Souk‎");
INSERT INTO villes (idVille, label) VALUES(395, "Tissa‎");
INSERT INTO villes (idVille, label) VALUES(396, "Tizi Ouasli‎");
INSERT INTO villes (idVille, label) VALUES(397, "Laayoune‎");
INSERT INTO villes (idVille, label) VALUES(398, "El Marsa‎");
INSERT INTO villes (idVille, label) VALUES(399, "Tarfaya‎");
INSERT INTO villes (idVille, label) VALUES(400, "Boujdour‎");
INSERT INTO villes (idVille, label) VALUES(401, "Awsard");
INSERT INTO villes (idVille, label) VALUES(402, "Oued-Eddahab");
INSERT INTO villes (idVille, label) VALUES(403, "Stehat");
INSERT INTO villes (idVille, label) VALUES(404, "Aït Attab");